Student Id : 2329861
Student Name : Anurag Sharma
Worksheet 00 - AI AND ML

Exercise on Functions

Task 1 : Create a Python program that converts between different units of measurement.

In [1]:
def convert_length(value, unit):
    """
    Transform length values between meters and feet.
    :param value: The numerical figure that needs conversion.
    :param unit: The unit of measurement ('m' for meters, 'ft' for feet).
    :return: The corresponding converted value.
    """
    if unit == 'm':
        return value * 3.28084  # Change meters to feet
    elif unit == 'ft':
        return value / 3.28084  # Change feet to meters
    else:
        raise ValueError("Invalid length unit provided.")

def convert_weight(value, unit):
    """
    Transform weight values between kilograms and pounds.
    :param value: The numerical figure that needs conversion.
    :param unit: The unit of measurement ('kg' for kilograms, 'lbs' for pounds).
    :return: The corresponding converted value.
    """
    if unit == 'kg':
        return value * 2.20462  # Convert kilograms to pounds
    elif unit == 'lbs':
        return value / 2.20462  # Convert pounds to kilograms
    else:
        raise ValueError("Invalid weight unit provided.")

def convert_volume(value, unit):
    """
    Transform volume values between liters and gallons.
    :param value: The numerical figure that needs conversion.
    :param unit: The unit of measurement ('L' for liters, 'gal' for gallons).
    :return: The corresponding converted value.
    """
    if unit == 'L':
        return value * 0.264172  # Change liters to gallons
    elif unit == 'gal':
        return value / 0.264172  # Change gallons to liters
    else:
        raise ValueError("Invalid volume unit provided.")

def main():
    """Core function to manage user interactions and perform conversions."""
    print("Unit Converter: Length, Weight, Volume")
    print("1. Length (meters to feet, feet to meters)")
    print("2. Weight (kilograms to pounds, pounds to kilograms)")
    print("3. Volume (liters to gallons, gallons to liters)")

    try:
        choice = int(input("Choose a conversion category (1-3): "))
        value = float(input("Input the value you wish to convert: "))

        if choice == 1:
            unit = input("Specify unit ('m' for meters, 'ft' for feet): ").strip().lower()
            result = convert_length(value, unit)
            new_unit = 'ft' if unit == 'm' else 'm'
        elif choice == 2:
            unit = input("Specify unit ('kg' for kilograms, 'lbs' for pounds): ").strip().lower()
            result = convert_weight(value, unit)
            new_unit = 'lbs' if unit == 'kg' else 'kg'
        elif choice == 3:
            unit = input("Specify unit ('L' for liters, 'gal' for gallons): ").strip().lower()
            result = convert_volume(value, unit)
            new_unit = 'gal' if unit == 'L' else 'L'
        else:
            print("Invalid option. Please select a number between 1 and 3.")
            return

        print(f"Converted result: {result:.2f} {new_unit}")

    except ValueError as e:
        print(f"Error encountered: {e}. Ensure proper input.")

if __name__ == "__main__":
    main()


Unit Converter: Length, Weight, Volume
1. Length (meters to feet, feet to meters)
2. Weight (kilograms to pounds, pounds to kilograms)
3. Volume (liters to gallons, gallons to liters)
Choose a conversion category (1-3): 1
Input the value you wish to convert: 1
Specify unit ('m' for meters, 'ft' for feet): ft
Converted result: 0.30 m


Task 2 : Create a Python program that performs various mathematical operations on a list of numbers.

In [2]:
def calculate_sum(numbers):
    """
    Compute the total sum of a given list of numbers.
    :param numbers: A collection of numerical values.
    :return: The computed sum.
    """
    return sum(numbers)

def calculate_average(numbers):
    """
    Compute the average from a list of numbers.
    :param numbers: A collection of numerical values.
    :return: The computed average.
    """
    return sum(numbers) / len(numbers) if numbers else 0  # Avoids division by zero

def find_maximum(numbers):
    """
    Identify the highest number in a given list.
    :param numbers: A collection of numerical values.
    :return: The highest value found.
    """
    return max(numbers)

def find_minimum(numbers):
    """
    Identify the smallest number in a given list.
    :param numbers: A collection of numerical values.
    :return: The lowest value found.
    """
    return min(numbers)

def main():
    """Primary function to accept user input and execute chosen operations."""
    print("Mathematical Operations on a List of Numbers")
    print("1. Sum")
    print("2. Average")
    print("3. Maximum")
    print("4. Minimum")

    try:
        choice = int(input("Select an operation (1-4): "))
        numbers = list(map(float, input("Enter numbers separated by spaces: ").split()))

        if not numbers:
            raise ValueError("List is empty. Please enter at least one number.")

        if choice == 1:
            result = calculate_sum(numbers)
            operation = "Sum"
        elif choice == 2:
            result = calculate_average(numbers)
            operation = "Average"
        elif choice == 3:
            result = find_maximum(numbers)
            operation = "Maximum"
        elif choice == 4:
            result = find_minimum(numbers)
            operation = "Minimum"
        else:
            print("Invalid option. Please select a number between 1 and 4.")
            return

        print(f"{operation}: {result:.2f}")

    except ValueError as e:
        print(f"Error: {e}. Ensure you enter valid numeric input.")

if __name__ == "__main__":
    main()


Mathematical Operations on a List of Numbers
1. Sum
2. Average
3. Maximum
4. Minimum
Select an operation (1-4): 2
Enter numbers separated by spaces: 2 229
Average: 115.50


Exercise on List Manipulation

Task 1 : Write a Python fuction that extracts every othrt elememt from a list, starting from the first element.

In [3]:
def extract_every_other(lst):
    """
    Retrieve every alternate element from the provided list, beginning with the first item.
    :param lst: A sequence of elements.
    :return: A new list containing every alternate element.
    """
    return lst[::2]  # Utilizing slicing to fetch every other element

# Demonstration
input_list = [1, 2, 3, 4, 5, 6]
output_list = extract_every_other(input_list)
print("Output:", output_list)  # Output: [1, 3, 5]


Output: [1, 3, 5]


Task 2 : Write a Python function that returns a sublist from a given list, starting from a specified index and ending at another specifed index.

In [4]:
def get_sublist(lst, start, end):
    """
    Extract a portion of the list from a specified start index to an end index (inclusive).
    :param lst: A sequence of elements.
    :param start: The beginning index.
    :param end: The ending index.
    :return: A sublist spanning from start to end (inclusive).
    """
    return lst[start:end+1]  # Slicing to ensure the end index is included

# Demonstration
input_list = [1, 2, 3, 4, 5, 6]
start_index = 2
end_index = 4
output_sublist = get_sublist(input_list, start_index, end_index)
print("Output:", output_sublist)  # Output: [3, 4, 5]

Output: [3, 4, 5]


Task 3 : Write a Python fuction that reverses a list using slicing.

In [5]:
def reverse_list(lst):
    """
    Reverse the order of elements in the given list using slicing.
    :param lst: A sequence of elements.
    :return: A new list with elements in reverse order.
    """
    return lst[::-1]  # Utilizing slicing to reverse the list

# Demonstration
input_list = [1, 2, 3, 4, 5]
output_list = reverse_list(input_list)
print("Output:", output_list)  # Output: [5, 4, 3, 2, 1]


Output: [5, 4, 3, 2, 1]


Task 4 : Write a Python fuction that removes the first and last elements of a list and returns the resulting sublist.

In [7]:
def remove_first_last(lst):
    """
    Remove the first and last elements from the list and return the resulting sublist.
    :param lst: List of elements.
    :return: Sublist without the first and last elements.
    """
    return lst[1:-1]  # Slicing to remove the first and last elements

# Example usage
input_list = [1, 2, 3, 4, 5]
output_list = remove_first_last(input_list)
print("Output:", output_list)  # Output: [2, 3, 4]


Output: [2, 3, 4]


Task 5 : Write a Python function that extracts the first n elements from a list.

In [8]:
def get_first_n(lst, n):
    """
    Retrieve the first n elements from the given list using slicing.
    :param lst: A sequence of elements.
    :param n: The number of elements to extract.
    :return: A new list containing the first n elements.
    """
    return lst[:n]  # Utilizing slicing to extract the first n elements

# Demonstration
input_list = [1, 2, 3, 4, 5]
n = 3
output_list = get_first_n(input_list, n)
print("Output:", output_list)  # Output: [1, 2, 3]

Output: [1, 2, 3]


Task 6 : Write a Python fuctions that extracts the first n elements from a list.

In [9]:
def get_last_n(lst, n):
    """
    Retrieve the last n elements from the given list using slicing.
    :param lst: A sequence of elements.
    :param n: The number of elements to extract from the end.
    :return: A new list containing the last n elements.
    """
    return lst[-n:]  # Utilizing slicing to extract the last n elements

# Demonstration
input_list = [1, 2, 3, 4, 5]
n = 2
output_list = get_last_n(input_list, n)
print("Output:", output_list)  # Output: [4, 5]


Output: [4, 5]


Task 7 : Write a Python function that extrats a list of elements in reverse order starting from the second-to-last element and skippig one element in between.

In [10]:
def reverse_skip(lst):
    """
    Extract every second element starting from the second-to-last element and moving backward.
    :param lst: List of elements.
    :return: A list of every second element in reverse order starting from the second-to-last.
    """
    return lst[-2::-2]  # Slicing to get every second element starting from the second-to-last, moving backward

# Example usage
input_list = [1, 2, 3, 4, 5, 6]
output_list = reverse_skip(input_list)
print("Output:", output_list)  # Output: [5, 3, 1]


Output: [5, 3, 1]


Exercise on Nested Loops

Task 1 : Write a Python fuctions that takes a nested list and flattens it into a single list, where all the elements are in a single dimension.

In [11]:
def flatten(lst):
    """
    Convert a nested list into a single-level list.
    :param lst: A nested list containing elements or other lists.
    :return: A new list with all elements flattened.
    """
    flattened = []
    for item in lst:
        if isinstance(item, list):
            flattened.extend(flatten(item))  # Recursively process nested lists
        else:
            flattened.append(item)
    return flattened

# Demonstration
nested_list = [[1, 2], [3, 4], [5]]
output = flatten(nested_list)
print("Output:", output)  # Output: [1, 2, 3, 4, 5]

Output: [1, 2, 3, 4, 5]


Task 2 : Write a Python functions that extracts a specific element from a nested list given its indices.

In [12]:
def access_nested_element(lst, indices):
    """
    Retrieve an element from a nested list using a sequence of indices.
    :param lst: A multi-dimensional list.
    :param indices: A list of indices specifying the path to the element.
    :return: The element located at the given indices.
    """
    for index in indices:
        lst = lst[index]  # Traverse the nested list using provided indices
    return lst

# Demonstration
nested_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
indices = [1, 2]
output = access_nested_element(nested_list, indices)
print("Output:", output)  # Output: 6

Output: 6


Task 3 : Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth).

In [13]:
def sum_nested(lst):
    """
    Calculate the sum of all elements in a nested list (regardless of depth).
    :param lst: Nested list of numbers.
    :return: Sum of all elements.
    """
    return sum(sum_nested(item) if isinstance(item, list) else item for item in lst)

# Example usage
nested_list = [[1, 2], [3, [4, 5]], 6]
output = sum_nested(nested_list)
print("Output:", output)  # Output: 21


Output: 21


Task 4 : Write a Python Function that removes all the occurances of a specific element from a nested list.

In [14]:
def remove_element(lst, elem):
    """
    Recursively traverse a nested list and eliminate all instances of the specified element.
    :param lst: The nested list to process.
    :param elem: The element to remove from the list.
    :return: A new list with all occurrences of 'elem' removed.
    """
    if isinstance(lst, list):
        # For each item in the list, apply remove_element recursively, unless it's the element to remove
        return [remove_element(item, elem) for item in lst if item != elem]
    return lst

# Example usage
nested_list = [[1, 2], [3, 2], [4, 5]]
elem = 2
output = remove_element(nested_list, elem)
print("Output:", output)  # Output: [[1], [3], [4, 5]]


Output: [[1], [3], [4, 5]]


Task 5 : Write a Python Function that finds the maximun element in a nested list (regardless of deepth).

In [15]:
def find_max(lst):
    """
    Recursively determine the largest element in a potentially nested list.
    :param lst: The nested list to examine.
    :return: The maximum value found in the list, even within nested sublists.
    """
    max_element = float('-inf')  # Start with the smallest possible value
    for item in lst:
        if isinstance(item, list):
            # If item is a list, dive deeper and compare the maximum values
            max_element = max(max_element, find_max(item))
        else:
            # For non-list elements, simply compare to find the largest
            max_element = max(max_element, item)
    return max_element

# Example usage
nested_list = [[1, 2], [3, [4, 5]], 6]
output = find_max(nested_list)
print("Output:", output)  # Output: 6


Output: 6


Task 6 : Write a Python function that counts how many times a specific appears in a nested list.

In [16]:
def count_occurrences(lst, elem):
    """
    Recursively count the number of times a given element appears within a nested list.
    :param lst: The list to search through, which can contain other lists.
    :param elem: The element whose occurrences are to be counted.
    :return: The total count of occurrences of the element in the list.
    """
    count = 0
    for item in lst:
        if isinstance(item, list):
            # If the item is a sublist, search within it recursively
            count += count_occurrences(item, elem)
        elif item == elem:
            # Increment count for each match with the target element
            count += 1
    return count

# Example usage
nested_list = [[1, 2], [2, 3], [2, 4]]
elem = 2
output = count_occurrences(nested_list, elem)
print("Output:", output)  # Output: 3


Output: 3


Task 7 : Write a Python function that flattens a list of lists of lists into a single list, regardless of deepth.

In [17]:
def deep_flatten(lst):
    """
    Recursively flatten a deeply nested list of lists into a single, flat list.
    :param lst: The nested list to flatten, which can contain any level of sublists.
    :return: A single, flat list containing all the elements.
    """
    flattened = []
    for item in lst:
        if isinstance(item, list):
            # For sublists, apply flattening recursively
            flattened.extend(deep_flatten(item))
        else:
            # For non-list items, append them directly to the result
            flattened.append(item)
    return flattened

# Example usage
nested_list = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
output = deep_flatten(nested_list)
print("Output:", output)  # Output: [1, 2, 3, 4, 5, 6, 7, 8]


Output: [1, 2, 3, 4, 5, 6, 7, 8]


Task 8 : Write a Python Function that calculates the average of all elements in a nested list.

In [18]:
def average_nested(lst):
    """
    Calculate the average of all elements in a nested list.
    :param lst: Nested list of numbers.
    :return: The average of all elements.
    """
    total, count = 0, 0
    for item in lst:
        if isinstance(item, list):
            sub_total, sub_count = average_nested(item)  # Recursively get sum and count
            total += sub_total
            count += sub_count
        else:
            total += item
            count += 1
    return total, count  # Return both total and count

# Example usage
nested_list = [[1, 2], [3, 4], [5, 6]]
total, count = average_nested(nested_list)
average = total / count if count else 0  # Avoid division by zero
print("Average:", average)  # Output: 3.5


Average: 3.5


TO-do Numpy


Problem 1 : Array Creation


Task 1 : Initialize an empty array with sizw 2*2:

In [19]:
import numpy as np
empty_array = np.empty((2, 2))
print("Empty Array:\n", empty_array)


Empty Array:
 [[2.10715747e-316 0.00000000e+000]
 [6.54829267e-310 6.54829267e-310]]


Task 2 : Initialize an empty array with size 4*2:

In [20]:
ones_array = np.ones((4, 2))
print("Ones Array:\n", ones_array)

Ones Array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


Task 3 : Return a new array of a given shape and type, filled with a fill value:

In [22]:
filled_array = np.full((3, 3), 7)
print("Filled Array:\n", filled_array)

Filled Array:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]


Task 4 : Return a new array of zeros with the same shape and type as a given array:

In [23]:
template_array = np.array([[1, 2], [3, 4]])
zeros_array = np.zeros_like(template_array)
print("Zeros Array with Same Shape and Type:\n", zeros_array)


Zeros Array with Same Shape and Type:
 [[0 0]
 [0 0]]


Task 5 : Return a new array of ones with the same shape type as a given array:

In [24]:
ones_like_array = np.ones_like(template_array)
print("Ones Array with Same Shape and Type:\n", ones_like_array)


Ones Array with Same Shape and Type:
 [[1 1]
 [1 1]]


Task 6 : Convert an existing list new_list = [1,2,3,4] to a numpy array:

In [25]:
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("Numpy Array:\n", numpy_array)


Numpy Array:
 [1 2 3 4]


Problem 2 : Array Manipulation

Task 1 : Create an array with values ranging from 10 to 49.

In [26]:
array_range = np.arange(10, 50)
print("Array with values from 10 to 49:\n", array_range)

Array with values from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


Task 2 : Create a 3*3 matrix with values ranging form 0 to 8.

In [28]:
matrix_3x3 = np.arange(9).reshape(3, 3)
print("3x3 Matrix with values from 0 to 8:\n", matrix_3x3)

3x3 Matrix with values from 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


Task 3 : Create a 3*3 identity matrix.

In [29]:
identity_matrix = np.eye(3)
print("3x3 Identity Matrix:\n", identity_matrix)


3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Task 4 : Create a random array of size 30 and find the mean of the array.

In [30]:
random_array = np.random.random(30)
mean_value = random_array.mean()
print("Mean of Random Array:", mean_value)


Mean of Random Array: 0.44571760927801835


Task 5 : Create a 10*10 array with random values and find the minimum and maximum values.

In [31]:
random_10x10 = np.random.random((10, 10))
min_value = random_10x10.min()
max_value = random_10x10.max()
print("Minimum Value:", min_value)
print("Maximum Value:", max_value)


Minimum Value: 0.00023412251168808407
Maximum Value: 0.9974606700578529


Task 6 : Create a zero array of size 10 and replace the 5th element with 1.

In [32]:
zero_array = np.zeros(10)
zero_array[4] = 1  # Index 4 corresponds to the 5th element
print("Zero Array with 5th Element as 1:\n", zero_array)


Zero Array with 5th Element as 1:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


Task 7 : Reverse an array

In [33]:
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("Reversed Array:\n", reversed_arr)

Reversed Array:
 [0 4 0 0 2 1]


Task 8 : Create a 2D array with 1 on the border and  inside:

In [34]:
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("2D Array with 1 on Border and 0 Inside:\n", border_array)

2D Array with 1 on Border and 0 Inside:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Task 9 : Create an 8*8 matrix and fill it with a checkboard pattern:

In [35]:
checkerboard = np.zeros((8, 8))
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("8x8 Checkerboard Pattern:\n", checkerboard)

8x8 Checkerboard Pattern:
 [[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


Problem 3: Array Operations

For the following arrays:

In [36]:
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

Task 1 : Add the two arrays x and y.

In [37]:
sum_array = x + y
print("Sum of Arrays x and y:\n", sum_array)

Sum of Arrays x and y:
 [[ 6  8]
 [10 13]]


Task 2 : Subtract the two arrays x and y.

In [38]:
diff_array = x - y
print("Difference of Arrays x and y:\n", diff_array)

Difference of Arrays x and y:
 [[-4 -4]
 [-4 -3]]


Task 3 : Multiply the array x with an integer of your choice.

In [39]:
multiplied_array = x * 3  # Example with 3
print("Array x Multiplied by 3:\n", multiplied_array)

Array x Multiplied by 3:
 [[ 3  6]
 [ 9 15]]


Task 4 : Find the square of each element of the array x.


In [40]:
squared_array = np.square(x)
print("Square of Each Element in Array x:\n", squared_array)

Square of Each Element in Array x:
 [[ 1  4]
 [ 9 25]]


Task 5 : Find the dot product.

In [41]:
dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)
print("Dot product of v and w:", dot_vw)
print("Dot product of x and v:\n", dot_xv)
print("Dot product of x and y:\n", dot_xy)

Dot product of v and w: 219
Dot product of x and v:
 [29 77]
Dot product of x and y:
 [[19 22]
 [50 58]]


Task 6 : Concatenate x and y along roes and concatenate v and w along columns.

In [42]:
concatenated_xy_row = np.concatenate((x, y), axis=0)
concatenated_vw_col = np.concatenate((v[:, None], w[:, None]), axis=1)
print("Concatenated x and y along rows:\n", concatenated_xy_row)
print("Concatenated v and w along columns:\n", concatenated_vw_col)


Concatenated x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenated v and w along columns:
 [[ 9 11]
 [10 12]]


Task 7 : Concatenate x and v:

In [43]:
 ## np.concatenate((x, v))
# This raises a value error because the dimensions does not match for conatenation

Problem 4 : Matrix Operations

For the following matrices:

In [44]:
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

Task 1 : Prove that A*A^(-1)=|.

In [45]:
A_inv = np.linalg.inv(A)
identity_matrix = np.dot(A, A_inv)
print("A * A^(-1) = I:\n", identity_matrix)

A * A^(-1) = I:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


Task 2 : Prove that AB = BA.

In [46]:
AB = np.dot(A, B)
BA = np.dot(B, A)
print("AB:\n", AB)
print("BA:\n", BA)

AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]


Task 3 : Prove thar (AB)^T = B^T*A^T.

In [47]:
transpose_AB = np.transpose(np.dot(A, B))
transpose_BA = np.dot(np.transpose(B), np.transpose(A))
print("(AB)^T:\n", transpose_AB)
print("B^T * A^T:\n", transpose_BA)

(AB)^T:
 [[23 51]
 [13 29]]
B^T * A^T:
 [[23 51]
 [13 29]]


Task 4 : Solve the system of linear equations using inverse methods.

In [51]:
A_eq = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B_eq = np.array([-1, -3, 9])

X = np.linalg.inv(A_eq).dot(B_eq)
print("Solution using Inverse Method:", X)

Solution using Inverse Method: [ 2.  1. -2.]


Problem 5 : How Fast is Numpy?

Task 1 : Element-wise Addition:

In [52]:
import time

# Using Python Lists
list1 = [i for i in range(1000000)]
list2 = [i for i in range(1000000)]
start_time = time.time()
list_addition = [list1[i] + list2[i] for i in range(1000000)]
print("Python List Addition Time:", time.time() - start_time)

# Using NumPy Arrays
array1 = np.array(list1)
array2 = np.array(list2)
start_time = time.time()
numpy_addition = array1 + array2
print("NumPy Array Addition Time:", time.time() - start_time)


Python List Addition Time: 0.15365219116210938
NumPy Array Addition Time: 0.00990915298461914


Task 2 : Element-wise Multiplication.

In [53]:
# Using Python Lists
start_time = time.time()
list_multiplication = [list1[i] * list2[i] for i in range(1000000)]
print("Python List Multiplication Time:", time.time() - start_time)

# Using NumPy Arrays
start_time = time.time()
numpy_multiplication = array1 * array2
print("NumPy Array Multiplication Time:", time.time() - start_time)


Python List Multiplication Time: 0.09975600242614746
NumPy Array Multiplication Time: 0.007064104080200195


Task 3: Dot Product:

In [54]:
# Using Python Lists
start_time = time.time()
dot_product_list = sum(list1[i] * list2[i] for i in range(1000000))
print("Python List Dot Product Time:", time.time() - start_time)

# Using NumPy Arrays
start_time = time.time()
dot_product_numpy = np.dot(array1, array2)
print("NumPy Array Dot Product Time:", time.time() - start_time)


Python List Dot Product Time: 0.19109797477722168
NumPy Array Dot Product Time: 0.002837657928466797


Task 4 : Matrix Multiplication

In [55]:
import time
import numpy as np

# Using Python Lists
matrix1 = [[i for i in range(1000)] for j in range(1000)]
matrix2 = [[i for i in range(1000)] for j in range(1000)]
start_time = time.time()
matrix_multiplication_list = [[sum(matrix1[i][k] * matrix2[k][j] for k in range(1000)) for j in range(1000)] for i in range(1000)]
print("Python List Matrix Multiplication Time:", time.time() - start_time)

# Using NumPy Arrays
matrix1_numpy = np.random.random((1000, 1000))
matrix2_numpy = np.random.random((1000, 1000))
start_time = time.time()
matrix_multiplication_numpy = np.dot(matrix1_numpy, matrix2_numpy)
print("NumPy Array Matrix Multiplication Time:", time.time() - start_time)

Python List Matrix Multiplication Time: 192.1754186153412
NumPy Array Matrix Multiplication Time: 0.06320023536682129
